# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDY4Y2IzZjFhZTc0NGY3ZGY4ZWU0ZWQ0MzQ2NDAwNjAzZWU1N2Q1MzBjYTllMTIwNjVkNzdjZDhhYTQ4N2Q5YTg1NjljYWMwZWU2NGViZTE1ZmIwMGFjNjE0M2Q0YWNiNmY4ODI5YmUxZDllZjhhNDMxOTllZjhiNjkxNmQyMjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
